//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhatApp {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImmoWhatApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ajouter un bien.
        /// </summary>
        public static string ajouterUnBien {
            get {
                return ResourceManager.GetString("ajouterUnBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à alarme.
        /// </summary>
        public static string alarm {
            get {
                return ResourceManager.GetString("alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à alarme.
        /// </summary>
        public static string alarme {
            get {
                return ResourceManager.GetString("alarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à année de construction.
        /// </summary>
        public static string anneeDeConstruction {
            get {
                return ResourceManager.GetString("anneeDeConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à appartement.
        /// </summary>
        public static string appartement {
            get {
                return ResourceManager.GetString("appartement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à boite.
        /// </summary>
        public static string boite {
            get {
                return ResourceManager.GetString("boite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chambre.
        /// </summary>
        public static string chambre {
            get {
                return ResourceManager.GetString("chambre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chambres.
        /// </summary>
        public static string chambres {
            get {
                return ResourceManager.GetString("chambres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à code postale.
        /// </summary>
        public static string codePostale {
            get {
                return ResourceManager.GetString("codePostale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à commune.
        /// </summary>
        public static string commune {
            get {
                return ResourceManager.GetString("commune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nom d&apos;utilisateur ou mot de pass pas valide.
        /// </summary>
        public static string connectionNotOk {
            get {
                return ResourceManager.GetString("connectionNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        public static string connectionOk {
            get {
                return ResourceManager.GetString("connectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à connexion reussie.
        /// </summary>
        public static string connectionReussie {
            get {
                return ResourceManager.GetString("connectionReussie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à connexion.
        /// </summary>
        public static string connexion {
            get {
                return ResourceManager.GetString("connexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cuisine équipée.
        /// </summary>
        public static string cuisineEquipee {
            get {
                return ResourceManager.GetString("cuisineEquipee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à déscription.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desole.
        /// </summary>
        public static string desole {
            get {
                return ResourceManager.GetString("desole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à double vitrage.
        /// </summary>
        public static string doubleVitrage {
            get {
                return ResourceManager.GetString("doubleVitrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à énergie.
        /// </summary>
        public static string energie {
            get {
                return ResourceManager.GetString("energie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à enregistrer.
        /// </summary>
        public static string enregistrer {
            get {
                return ResourceManager.GetString("enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à envoyer.
        /// </summary>
        public static string envoyer {
            get {
                return ResourceManager.GetString("envoyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à étage.
        /// </summary>
        public static string etage {
            get {
                return ResourceManager.GetString("etage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à étages.
        /// </summary>
        public static string etages {
            get {
                return ResourceManager.GetString("etages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à jardin.
        /// </summary>
        public static string jardin {
            get {
                return ResourceManager.GetString("jardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le bien a bien été enregistré.
        /// </summary>
        public static string LeBienABienEteEnregistre {
            get {
                return ResourceManager.GetString("LeBienABienEteEnregistre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à le bien existe déja.
        /// </summary>
        public static string LeBienExisteDeja {
            get {
                return ResourceManager.GetString("LeBienExisteDeja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à déscription.
        /// </summary>
        public static string libelleDescription {
            get {
                return ResourceManager.GetString("libelleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à maison.
        /// </summary>
        public static string maison {
            get {
                return ResourceManager.GetString("maison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à buanderies.
        /// </summary>
        public static string nbBuanderie {
            get {
                return ResourceManager.GetString("nbBuanderie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à caves.
        /// </summary>
        public static string nbCave {
            get {
                return ResourceManager.GetString("nbCave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chambre(s).
        /// </summary>
        public static string nbChambres {
            get {
                return ResourceManager.GetString("nbChambres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à dressings.
        /// </summary>
        public static string nbDressing {
            get {
                return ResourceManager.GetString("nbDressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nombre d&apos;étages.
        /// </summary>
        public static string nbEtages {
            get {
                return ResourceManager.GetString("nbEtages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à places de garage.
        /// </summary>
        public static string nbGarage {
            get {
                return ResourceManager.GetString("nbGarage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à greniers.
        /// </summary>
        public static string nbGrenier {
            get {
                return ResourceManager.GetString("nbGrenier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nombre de photos.
        /// </summary>
        public static string nbPhotos {
            get {
                return ResourceManager.GetString("nbPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à salons.
        /// </summary>
        public static string nbSalon {
            get {
                return ResourceManager.GetString("nbSalon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à salles à manger.
        /// </summary>
        public static string nbSam {
            get {
                return ResourceManager.GetString("nbSam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à salles de bain.
        /// </summary>
        public static string nbSdb {
            get {
                return ResourceManager.GetString("nbSdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à toilettes.
        /// </summary>
        public static string nbToilette {
            get {
                return ResourceManager.GetString("nbToilette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vérandas.
        /// </summary>
        public static string nbVeranda {
            get {
                return ResourceManager.GetString("nbVeranda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à numero.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parking.
        /// </summary>
        public static string parking {
            get {
                return ResourceManager.GetString("parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pièces.
        /// </summary>
        public static string pieces {
            get {
                return ResourceManager.GetString("pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à piscine.
        /// </summary>
        public static string piscine {
            get {
                return ResourceManager.GetString("piscine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à prix.
        /// </summary>
        public static string prix {
            get {
                return ResourceManager.GetString("prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à rue.
        /// </summary>
        public static string rue {
            get {
                return ResourceManager.GetString("rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à s&apos;enregistrer.
        /// </summary>
        public static string SEnregistrer {
            get {
                return ResourceManager.GetString("SEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3 clics pour tout savoir sur vos m².
        /// </summary>
        public static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à superficie.
        /// </summary>
        public static string superficie {
            get {
                return ResourceManager.GetString("superficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à supprimé.
        /// </summary>
        public static string supprime {
            get {
                return ResourceManager.GetString("supprime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à terrain.
        /// </summary>
        public static string terrain {
            get {
                return ResourceManager.GetString("terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à type de bien.
        /// </summary>
        public static string typeBien {
            get {
                return ResourceManager.GetString("typeBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vendu.
        /// </summary>
        public static string vendu {
            get {
                return ResourceManager.GetString("vendu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à villa.
        /// </summary>
        public static string villa {
            get {
                return ResourceManager.GetString("villa", resourceCulture);
            }
        }
    }
}
