//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIEN()
        {
            this.BIEN_PHOTOS = new HashSet<BIEN_PHOTOS>();
            this.BIEN_PIECES = new HashSet<BIEN_PIECES>();
            this.OPTIONS = new HashSet<OPTIONS>();
        }
    
        public int BIEN_Id { get; set; }
        public int BIEN_IdType { get; set; }
        public int BIEN_IdProprietaire { get; set; }
        public int BIEN_Prix { get; set; }
        public int BIEN_Superficie { get; set; }
        public int BIEN_idCommune { get; set; }
        public string Bien_Rue { get; set; }
        public string BIEN_Numero { get; set; }
        public string BIEN_Boite { get; set; }
        public bool BIEN_Vendu { get; set; }
        public bool BIEN_Supprime { get; set; }
        public int BIEN_Etages { get; set; }
        public string BIEN_Libelle { get; set; }
        public int BIEN_AnneeDeConstruction { get; set; }
        public string BIEN_Energie { get; set; }
        public int BIEN_PhotoPrincipale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIEN_PHOTOS> BIEN_PHOTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIEN_PIECES> BIEN_PIECES { get; set; }
        public virtual COMMUNE COMMUNE { get; set; }
        public virtual MEMBRE MEMBRE { get; set; }
        public virtual TYPEBIEN TYPEBIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPTIONS> OPTIONS { get; set; }
    }
}
