//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN_PIECES
    {
        public int idBien { get; set; }
        public int idPiece { get; set; }
        public int nombre { get; set; }
    
        public virtual BIEN BIEN { get; set; }
        public virtual PIECES PIECES { get; set; }
    }
}
