//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN_OPTION
    {
        public int IdBien { get; set; }
        public int IdOption { get; set; }
        public bool estPresent { get; set; }
    
        public virtual BIEN BIEN { get; set; }
        public virtual OPTIONS OPTIONS { get; set; }
    }
}
