//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMUNE_Prenoms
    {
        public int IdCommune { get; set; }
        public string NomCommuneFR { get; set; }
        public string NomCommuneNL { get; set; }
        public string Prenom { get; set; }
        public int NombreDePersonnes { get; set; }
        public string Sexe { get; set; }
    }
}
