//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail
    {
        public int idMail { get; set; }
        public string adresseMail { get; set; }
        public System.DateTime dateEnvoi { get; set; }
        public string sujet { get; set; }
        public string msg { get; set; }
        public bool lu { get; set; }
        public Nullable<System.DateTime> repondu { get; set; }
        public int idProprietaire { get; set; }
    
        public virtual MEMBRE MEMBRE { get; set; }
    }
}
