//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBRE()
        {
            this.BIEN = new HashSet<BIEN>();
            this.Connections = new HashSet<Connections>();
            this.mail1 = new HashSet<mail>();
        }
    
        public int idMembre { get; set; }
        public string mail { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string Commune { get; set; }
        public string rue { get; set; }
        public string numero { get; set; }
        public string boite { get; set; }
        public System.DateTime dateDeNaissance { get; set; }
        public bool estProprietaire { get; set; }
        public string photo { get; set; }
        public bool deleted { get; set; }
        public string idUser { get; set; }
        public System.DateTime DateEnregistrement { get; set; }
        public Nullable<System.DateTime> DateSuppression { get; set; }
        public string RoleMembre { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIEN> BIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Connections> Connections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mail> mail1 { get; set; }
    }
}
