//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAT_COMMUNES
    {
        public int IdCommune { get; set; }
        public string NomCommuneNL { get; set; }
        public string NomCommuneFR { get; set; }
        public int IdArrondissement { get; set; }
        public string ArrondissementNL { get; set; }
        public string ArrondissementFR { get; set; }
        public int IdProvince { get; set; }
        public string ProvinceNL { get; set; }
        public string ProvinceFR { get; set; }
        public int IdRegion { get; set; }
        public string RegionNL { get; set; }
        public string RegionFR { get; set; }
        public string SEXE { get; set; }
        public string CodeNational { get; set; }
        public string NationaliteFR { get; set; }
        public string NationaliteNL { get; set; }
        public int CodeEtatCivil { get; set; }
        public string EtatCivilFR { get; set; }
        public string EtatCivilNL { get; set; }
        public int Age { get; set; }
        public int NombreDePersonnes { get; set; }
        public int AnneeDeReference { get; set; }
    }
}
