//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatImmo
    {
        public string codePostal { get; set; }
        public int refnis { get; set; }
        public string localite { get; set; }
        public int annee { get; set; }
        public string trimestre { get; set; }
        public string classeDeSuperficie { get; set; }
        public int Maison_nbTransactions { get; set; }
        public int Maison_prixTotal { get; set; }
        public int Maison_superficieTotal { get; set; }
        public int Maison_prixMoyen { get; set; }
        public int Maison_P10Prix { get; set; }
        public int Maison_Q25Prix { get; set; }
        public int Maison_Q50Prix { get; set; }
        public int Maison_Q75Prix { get; set; }
        public int Maison_P90Prix { get; set; }
        public int Villa_nbTransactions { get; set; }
        public int Villa_prixTotal { get; set; }
        public int Villa_superficieTotale { get; set; }
        public int Villa_prixMoyen { get; set; }
        public int Villa_P10Prix { get; set; }
        public int Villa_Q25Prix { get; set; }
        public int Villa_Q50Prix { get; set; }
        public int Villa_Q75Prix { get; set; }
        public int Villa_P90Prix { get; set; }
        public int Appart_nbTransactions { get; set; }
        public int Appart_prixTotal { get; set; }
        public int Appart_superficieTotale { get; set; }
        public int Appart_prixMoyen { get; set; }
        public int Appart_P10Prix { get; set; }
        public int Appart_Q25Prix { get; set; }
        public int Appart_Q50Prix { get; set; }
        public int Appart_Q75Prix { get; set; }
        public int Appart_P90Prix { get; set; }
        public int Terrain_nbTransactions { get; set; }
        public int Terrain_prixTotal { get; set; }
        public int Terrain_superficieTotale { get; set; }
        public int Terrain_prixMoyen { get; set; }
        public int Terrain_P10Prix { get; set; }
        public int Terrain_Q25Prix { get; set; }
        public int Terrain_Q50Prix { get; set; }
        public int Terrain_Q75Prix { get; set; }
        public int Terrain_P90Prix { get; set; }
    }
}
