//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableJSON
    {
        public int Id { get; set; }
        public string CodePostal { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public Nullable<int> GMapPartRecord_Id { get; set; }
        public Nullable<int> StartZoom { get; set; }
        public Nullable<int> StopZoom { get; set; }
        public string Commune { get; set; }
        public string Quarter { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ColorA { get; set; }
        public string ColorT { get; set; }
        public string ColorV { get; set; }
        public Nullable<decimal> PriceA { get; set; }
        public Nullable<decimal> PriceT { get; set; }
        public Nullable<decimal> PriceV { get; set; }
        public Nullable<decimal> CenterLat { get; set; }
        public Nullable<decimal> CenterLng { get; set; }
    }
}
