//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmoWhat_API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VAL_PRIX_MOYEN_BIEN
    {
        public int idType { get; set; }
        public Nullable<int> idCouleur { get; set; }
        public Nullable<int> valMin { get; set; }
        public Nullable<int> valMax { get; set; }
        public int idClasse { get; set; }
    
        public virtual RefCouleur RefCouleur { get; set; }
        public virtual TYPEBIEN TYPEBIEN { get; set; }
    }
}
